output HDMI-A-1 mode 2560x1440 pos 0 0
# output HDMI-A-1 mode 3840x2160 pos 0 0
# output HDMI-A-1 scale 1.5
output HDMI-A-1 scale 1
output HDMI-A-1 transform 90
# output DP-1 mode 2560x1440 pos 1440 1120
# output DP-2 mode 2560x1440 pos 4000 1120
output DP-2 mode 2560x1440 pos 1440 1120
output DP-1 mode 2560x1440 pos 4000 1120

# Left monitor (portrait 4k)
workspace 10 output HDMI-A-1

# Middle monitor (landscape 1440p)
workspace 4 output DP-2

# Right monitor (landscape 1440p)
workspace 9 output DP-1

# assign [app_id="com.chatterino.chatterino"] workspace 8
