#!/bin/sh

set -eu

hosts_dir="/etc/hosts.d"
hosts_file="/etc/hosts"
hosts_file_bkp="/etc/hosts.rollingbkp"
tmp_file="$(mktemp)"

[ -f "$hosts_file" ] && sudo cp "$hosts_file" "$hosts_file_bkp"

{ echo "# This file is generated by $0 - It takes all entries from /etc/hosts.d/*.conf and concatenates them.";
    echo "# Any changes made here will be lost next time the script is run"; } >> "$tmp_file"

for f in $(find "$hosts_dir" -type f -iname "*.conf" | sort); do
    { echo "# From file $f";
    cat "$f";
    printf "\n\n"; } >> "$tmp_file"
done

sudo chown root:root "$tmp_file"
sudo chmod 0644 "$tmp_file"
sudo mv "$tmp_file" "$hosts_file"
